name: Cloud Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Clean Server Storage Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc

    - name: Install Correct Android Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf libxml2-utils lzop rsync unzip zip openjdk-11-jdk python3

    - name: Setup Google Repo Command
      run: |
        mkdir -p ~/bin
        curl https://googleapis.com > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Set Identity Config
      run: |
        git config --global user.name "HelixOS-Builder"
        git config --global user.email "helix@cloud.local"

    - name: Setup Build Directory and Initialize
      run: |
        mkdir workspace
        cd workspace
        repo init -u https://googlesource.com -b android-11.0.0_r48 --depth=1
        echo "Environment initialized successfully! Ready for code sync."
